name: CI Test

on: ["push"]
jobs:
  ci:
    runs-on: ubuntu
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.x

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: go test./...
